# Generated by Django 5.2.6 on 2025-10-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Author's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Author's last name", max_length=50)),
                ('biography', models.TextField(blank=True, help_text='Author biography', null=True)),
                ('nationality', models.CharField(blank=True, help_text='Author nationality', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'author',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, help_text='ISBN-13 number', max_length=13, null=True, unique=True)),
                ('title', models.CharField(help_text='Book title', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Book subtitle', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Book description', null=True)),
                ('publication_date', models.DateField(blank=True, help_text='Publication date', null=True)),
                ('edition', models.CharField(blank=True, help_text='Book edition', max_length=50, null=True)),
                ('pages', models.IntegerField(blank=True, help_text='Number of pages', null=True)),
                ('language', models.CharField(default='English', help_text='Book language', max_length=50)),
                ('total_copies', models.IntegerField(default=1, help_text='Total number of copies')),
                ('quantity', models.IntegerField(default=1, help_text='Available quantity')),
                ('cover_image_url', models.URLField(blank=True, help_text='Cover image URL', max_length=500, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed')], default='available', help_text='Current availability status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(help_text='Publisher name', max_length=100, unique=True)),
                ('address', models.TextField(blank=True, help_text='Publisher address', null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text='Publisher website', max_length=255, null=True)),
                ('established_year', models.IntegerField(blank=True, help_text='Year the publisher was established', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'db_table': 'publisher',
                'ordering': ['publisher_name'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.book')),
            ],
            options={
                'db_table': 'dashboard_borrowrecord',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='common.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['category_name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(help_text='Book category', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='common.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(help_text='Book publisher', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='common.publisher'),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('primary', 'Primary Author'), ('co-author', 'Co-Author'), ('editor', 'Editor'), ('translator', 'Translator')], default='primary', help_text='Role of the author in this book', max_length=20)),
                ('author', models.ForeignKey(help_text='Author reference', on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='common.author')),
                ('book', models.ForeignKey(help_text='Book reference', on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='common.book')),
            ],
            options={
                'verbose_name': 'Book Author',
                'verbose_name_plural': 'Book Authors',
                'db_table': 'book_author',
                'ordering': ['book', 'author'],
                'unique_together': {('book', 'author')},
            },
        ),
    ]
