# Generated by Django 5.2.6 on 2025-10-17 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book title/name', max_length=255)),
                ('type', models.CharField(help_text='Book type/genre', max_length=100)),
                ('language', models.CharField(default='English', help_text='Book language', max_length=50)),
                ('quantity', models.IntegerField(default=1, help_text='Total number of copies')),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], default='Available', help_text='Current availability status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_book',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.book')),
            ],
            options={
                'db_table': 'dashboard_borrowrecord',
            },
        ),
    ]
