# Generated by Django 5.2.6 on 2025-11-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_author_options_remove_author_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='User ID who performed the search')),
                ('search_query', models.CharField(help_text='Search query text', max_length=255)),
                ('search_type', models.CharField(choices=[('general', 'General Search'), ('title', 'Title Search'), ('author', 'Author Search'), ('category', 'Category Search')], default='general', help_text='Type of search performed', max_length=20)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text="Author's name", max_length=100),
        ),
    ]
