# Generated by Django 5.2.6 on 2025-11-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_searchhistory_alter_publisher_options_and_more'),
    ]

    operations = [
        # Drop the existing search_history table if it exists
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS search_history CASCADE;",
            reverse_sql="",  # No reverse operation needed
        ),
        # Recreate the search_history table with proper structure
        migrations.RunSQL(
            sql="""
            CREATE TABLE search_history (
                id SERIAL PRIMARY KEY,
                user_id INTEGER NOT NULL,
                search_query VARCHAR(255) NOT NULL,
                search_type VARCHAR(20) NOT NULL DEFAULT 'general',
                results_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX idx_search_history_user_id ON search_history(user_id);
            CREATE INDEX idx_search_history_created_at ON search_history(created_at DESC);
            """,
            reverse_sql="DROP TABLE IF EXISTS search_history CASCADE;",
        ),
    ]
