# Generated by Django 5.2.6 on 2025-11-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_fix_search_history_table'),
    ]

    operations = [
        # Remove SearchHistory model from the app state without dropping the underlying table.
        # The physical table 'search_history' is now owned by the dedicated 'search_history' app.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='SearchHistory',
                ),
            ],
        ),
    ]
