# Generated by Django 5.2.6 on 2025-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_delete_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='renewal_count',
            field=models.IntegerField(default=0, help_text='Number of times this book has been renewed'),
        ),
    ]
