# Generated by Django 5.2.6 on 2025-10-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
