# Generated by Django 5.2.6 on 2025-10-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(default='ShelfSmart Library', help_text='Name of the library', max_length=255)),
                ('theme', models.CharField(default='default', help_text='UI theme preference', max_length=50)),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('default_borrow_days', models.IntegerField(default=14, help_text='Default number of days for borrowing books')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
