# Generated by Django 5.2.6 on 2025-11-15 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='default_borrow_days',
            field=models.IntegerField(default=14, help_text='Default number of days for borrowing books (1-60)', validators=[django.core.validators.MinValueValidator(1, 'Minimum borrow days is 1'), django.core.validators.MaxValueValidator(60, 'Maximum borrow days is 60')]),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('light', 'Light')], default='default', help_text='UI theme preference', max_length=50),
        ),
    ]
