# Generated by Django 5.2.6 on 2025-11-15 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_appsettings_default_borrow_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='max_renewals',
            field=models.IntegerField(default=2, help_text='Maximum number of times a book can be renewed (0-5)', validators=[django.core.validators.MinValueValidator(0, 'Minimum renewals is 0'), django.core.validators.MaxValueValidator(5, 'Maximum renewals is 5')]),
        ),
    ]
