# Generated by Django 5.2.6 on 2025-11-15 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(help_text='Search query text', max_length=255)),
                ('search_type', models.CharField(choices=[('general', 'General Search'), ('title', 'Title Search'), ('author', 'Author Search'), ('category', 'Category Search')], default='general', help_text='Type of search performed', max_length=20)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results found')),
                ('search_context', models.CharField(default='catalog', help_text='Context where search was performed (catalog, admin, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed the search', on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'), models.Index(fields=['search_context', '-created_at'], name='search_hist_search__570f78_idx')],
            },
        ),
    ]
