# Generated by Django 5.2.6 on 2025-11-15 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add search_context column to existing table
        migrations.RunSQL(
            sql="""
            -- Add search_context column with default value if it doesn't exist
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='search_history' AND column_name='search_context') THEN
                    ALTER TABLE search_history ADD COLUMN search_context VARCHAR(50) DEFAULT 'catalog';
                END IF;
            END $$;
            
            -- Create indexes for better performance
            CREATE INDEX IF NOT EXISTS idx_search_history_user_created ON search_history(user_id, created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_search_history_context_created ON search_history(search_context, created_at DESC);
            """,
            reverse_sql="""
            -- Reverse migration
            DROP INDEX IF EXISTS idx_search_history_user_created;
            DROP INDEX IF EXISTS idx_search_history_context_created;
            ALTER TABLE search_history DROP COLUMN IF EXISTS search_context;
            """
        ),
        # Create the Django model state to match the altered table
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(help_text='Search query text', max_length=255)),
                ('search_type', models.CharField(choices=[('general', 'General Search'), ('title', 'Title Search'), ('author', 'Author Search'), ('category', 'Category Search')], default='general', help_text='Type of search performed', max_length=20)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results found')),
                ('search_context', models.CharField(default='catalog', help_text='Context where search was performed (catalog, admin, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed the search', on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
