# Generated by Django 5.2.6 on 2025-11-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_history', '0001_migrate_existing_search_history'),
    ]

    operations = [
        # Add search_context column to existing search_history table
        migrations.RunSQL(
            sql="ALTER TABLE search_history ADD COLUMN search_context VARCHAR(50) DEFAULT 'catalog';",
            reverse_sql="ALTER TABLE search_history DROP COLUMN search_context;"
        ),
    ]
